Project Root Folder/routes/auth.py
from flask import Blueprint, url_for,render_template,session ,request,redirect
import sqlite3



auth_bp = Blueprint('auth', __name__, url_prefix='/auth')


@auth_bp.route('/user_login')
def user_login():
    
    return render_template('auth/user_login.html')

@auth_bp.route('/admin_login')
def admin_login():
    
    return render_template('auth/admin_login.html')


@auth_bp.route('/admin_login_check',methods=['GET', 'POST'])
def admin_login_check():
    
        if request.method == 'POST':
           username = request.form['username']
           password = request.form['password']

        
           con = sqlite3.connect('database.db')
           cursor = con.cursor()

        
           cursor.execute("SELECT * FROM admins WHERE username = ? AND password = ?", (username,password))
           user = cursor.fetchone()
           con.close()
           

           if user:
            # Successful login
            
                return redirect(url_for('admin.admin_dashboard'))
           else:
           
              return "Invalid credentials"
           
    




@auth_bp.route('/user_login_check', methods=['GET', 'POST'])
def user_login_check():
    if request.method == 'POST':
        password =  request.form['password']
        username = request.form['username']
        

        con = sqlite3.connect('database.db')
        cursor = con.cursor()

        
        cursor.execute("  select * from users where username = ? AND password = ?", (username,password))
        user = cursor.fetchone()
        con.close()
        

        if user:
            session['username'] = user[0]
            return redirect(url_for('user_bp.user_home'))
        else:
            
            return "Wrong credentials"
    
    
        

Project Root Folder/routes/user_routes.py
from flask import Blueprint, render_template,request,redirect,url_for,session
import sqlite3


user_bp = Blueprint('user_bp', __name__, url_prefix='/')

def get_products():
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    cursor.execute("select  * FROM products")
    products = cursor.fetchall()
    con.close()
    
    return products

def get_categories():
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    cursor.execute(" select *  from categories")
    categories = cursor.fetchall()
    con.close()
    return categories

def get_category_name(category_id):
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    
    cursor.execute("select category_name from categories where category_id = ?", (category_id,))
    category_name = cursor.fetchone()[0]  # Fetches the first column of the result (category_name)
    
    con.close()
    
    return category_name
    

    

@user_bp.route('/user_home')
def user_home():
    products = get_products()
    categories=get_categories()
    latest_products = sorted(products,reverse=True)
    
    
    return render_template('/user_home/user_home.html', products=products,categories=categories,get_category_name=get_category_name, latest_products=latest_products)



@user_bp.route('/out_of_stock')
def out_of_stock():
    return render_template('/messages/outofstock.html')

@user_bp.route('/thank_you')
def  thank_you():
    return render_template('/messages/thanks.html')





def get_cart():
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    username = get_user_id_from_session()    
    cursor.execute("select * from  cart where username=?",(username,))
    cart = cursor.fetchall()
    con.close()
    
    return cart

@user_bp.route('/user_cart')
def user_cart():
    cart=get_cart()
    
    return render_template('/user_home/user_cart.html',cart=cart)


    

@user_bp.route('/add_to_cart', methods=['POST'])
def add_to_cart():
    product_id = int(request.form['product_id'])
    quantity = int(request.form['quantity'])
    username = get_user_id_from_session()
    price = int(request.form['price'])
    product_name = request.form['product_name']

    if username is None:
        # Redirects to login if user is not logged in
        return redirect(url_for('auth_bp.login'))

    con = sqlite3.connect('database.db')
    cursor = con.cursor()

    cursor.execute("SELECT * FROM cart WHERE username = ? AND product_id = ?", (username, product_id))
    cart_row = cursor.fetchone()

    if cart_row:
        cart_id = cart_row[0]
        new_quantity = cart_row[3] + quantity  
        cursor.execute("update cart set quantity = ?, price = ? WHERE cart_id = ?", (new_quantity, price, cart_id))
    else:
        
        cursor.execute("insert into cart (username, product_id, quantity, price, product_name) VALUES (?, ?, ?, ?, ?)",
                       (username, product_id, quantity, price, product_name))
    con.commit()
    con.close()

    return redirect(url_for('user_bp.user_home'))


def get_user_id_from_session():
      return session.get('username')
  



#Toughesr part in the code
#first it fetches all cart items from current user
#Then checks if quantity is available in products table or not
# Then gives suitable errors if there is a problem
#If no error then updates quantity in products table
#then creates a new order in user-ORDERS table
#At the end cart item is deleted
#and user gets Thank you message

@user_bp.route('/buy_now', methods=['POST'])
def buy_now():
    con = sqlite3.connect('database.db')
    cursor = con.cursor()    
    username = get_user_id_from_session()
    cursor.execute("SELECT product_id, quantity FROM cart WHERE username = ?", (username,))
    cart_data = cursor.fetchall()
    
    
    
    for product_id, cart_quantity in cart_data:
          cursor.execute("select  quantity, price, product_name from   products where product_id = ?", (product_id,))
          product_data = cursor.fetchone()
          product_quantity, price, product_name = product_data
          
          if product_quantity == 0:
                con.close()
                return redirect(url_for('user_bp.out_of_stock'))
            
            
          if (cart_quantity > product_quantity):
            con.close()
            return "Error: You are trying to buy more than available quantity."
    
        
          else:
            new_quantity = product_quantity - cart_quantity
          
        
            cursor.execute("insert into user_orders (username, product_id, quantity, price, product_name) values(?, ?, ?, ?,?)",
            (username, product_id, cart_quantity,price, product_name))
          
            cursor.execute("update products set quantity = ? WHERE product_id = ?", (new_quantity, product_id))
          
            cursor.execute("delete from cart where username = ?", (username,))
            con.commit()
            con.close()
            return redirect(url_for('user_bp.thank_you'))





#deleting an item from cart giving providing cart id
@user_bp.route('/remove_from_cart/<int:cart_id>', methods=['POST'])
def remove_from_cart(cart_id):
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    username = get_user_id_from_session()
    
    cursor.execute("delete from cart where username = ? AND cart_id = ?", (username, cart_id))
    
    con.commit()
    con.close()
    
    return redirect(url_for('user_bp.user_cart'))






def get_orders():
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    username = get_user_id_from_session()    
    cursor.execute("select * from user_orders where username=?",(username,))
    orders = cursor.fetchall()
    con.close()
    
    return orders

@user_bp.route('/user_orders')
def user_orders():
    orders=get_orders()
    
    return render_template('/user_home/user_orders.html',orders=orders)

#categories and products table is joined on category_id so that we can fetch category name too
#this function searches required data  

def perform_search(query):
    con = sqlite3.connect('database.db')
    cursor = con.cursor()
    
    
    cursor.execute("""
        select p.*, c.category_name from products as p
        join categories as c ON p.category_id = c.category_id
        WHERE p.product_name like ? OR p.price like ? OR c.category_name like ?
    """, ('%' + query + '%', '%' + query + '%', '%' + query + '%'))
    
    results = cursor.fetchall()
    con.close()
    
    return results

@user_bp.route('/search_results', methods=['GET'])
def search_results():
    query = request.args.get('query')
    
    # Performing a search 
    results = perform_search(query)
    products = get_products()
    categories=get_categories()

    
    
    return render_template('/user_home/search_results.html', results=results, query=query,get_category_name=get_category_name)



    
    

Project Root Folder/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />

  <link rel="stylesheet" type="text/css" href="../static/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <title>Document</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand"  > <b>Pepe Grocery Store </b>  </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('index') }}">Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('admin.admin_dashboard')}}">

                Admin Home
              </a>
        
        </div>
      </div>
    </nav>



    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>


    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>

      
  </body>
</html>




Project Root Folder/templates/home.html

{%block content%}
<style>

body{
  background-image: url(static/images/Home.jpg); 
        
  background-repeat: no-repeat;
        

}
</style>




<link
href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
rel="stylesheet"
integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
crossorigin="anonymous"
/>





</div>
<br>
<center>


    <a href ="{{ url_for('auth.user_login') }}">

        <button type="button" class="btn btn-secondary btn-lg">
          User Login
        </button>
      
      </a>


      <a href ="{{ url_for('auth.admin_login') }}">

        <button type="button" class="btn btn-secondary btn-lg">
          Admin Login
        </button>
      
      </a>
      
      

</center>






<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous"></script>

{%endblock%}

Project Root Folder/templates/user_base.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />

  <link rel="stylesheet" type="text/css" href="static/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">



  
    <title>Document</title>
  </head>
  <body>


    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" ><b>Pepe Grocery Store </b></a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('user_bp.user_home') }}">My Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('user_bp.user_cart')}}"> My Cart</a>
            </li>
              

            <li class="nav-item">
              <a class="nav-link" href="{{url_for('user_bp.user_orders')}}"> My Orders</a>
            </li>
          </ul>


          <form class="d-flex" action="{{ url_for('user_bp.search_results') }}" method="GET">
            <input
              class="form-control me-2"
              type="search"
              name="query"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>

          
        </div>
      </div>
    </nav>



    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>


    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>

  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>




